apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: apia
  name: apia-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: apia
  type: LoadBalancer
status:
  loadBalancer: {}
